name: Go CI

on:
  push:
    branches: [ main, homework_* ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25.1

    - name: Download dependencies
      run: make deps

    - name: Install golangci-lint
      run: |
        curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.8.0

    - name: Run lint
      run: make lint

    #интеграционным тестам нужен докер    
    - name: Check Docker
      env:
        TESTCONTAINERS_RYUK_DISABLED: true
      run: docker info

    - name: Run test
      run: make test

    - name: Build check
      run: make build-check
